package com.crimeanalyzer.util;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Standalone runner for generating the synthetic Chennai crime dataset.
 */
public class StandaloneDataGenerator {

    private static final long SEED = 20240101L;

    private static final String CSV_HEADER =
            "crime_id,date,time,year,month,day_of_week,hour,area,zone,crime_type," +
                    "severity,latitude,longitude,description,case_status";

    private static final String METADATA_COMMENT =
            "# SYNTHETIC DATASET - GENERATED FOR ACADEMIC DEMONSTRATION ONLY\n" +
                    "# This data does NOT represent official Chennai crime statistics.\n" +
                    "# Generated by: Chennai Crime Pattern Analyzer (College Capstone Project)\n" +
                    "# Fixed seed: " + SEED + " - Dataset is fully reproducible.\n";

    record SimpleLocation(String name, String zone, double lat, double lon) {}

    private static final List<SimpleLocation> CHENNAI_LOCATIONS = List.of(
            new SimpleLocation("Anna Nagar",      "North",      13.0850, 80.2101),
            new SimpleLocation("T Nagar",         "Central",    13.0418, 80.2341),
            new SimpleLocation("Adyar",           "South",      13.0012, 80.2565),
            new SimpleLocation("Velachery",       "South",      12.9815, 80.2180),
            new SimpleLocation("Tambaram",        "South West", 12.9249, 80.1000),
            new SimpleLocation("Guindy",          "Central",    13.0067, 80.2206),
            new SimpleLocation("Egmore",          "Central",    13.0732, 80.2609),
            new SimpleLocation("Mylapore",        "Central",    13.0368, 80.2676),
            new SimpleLocation("Perambur",        "North",      13.1142, 80.2329),
            new SimpleLocation("Ambattur",        "North West", 13.1143, 80.1548),
            new SimpleLocation("Porur",           "West",       13.0359, 80.1573),
            new SimpleLocation("Sholinganallur",  "South East", 12.9010, 80.2279),
            new SimpleLocation("Thoraipakkam",    "South East", 12.9244, 80.2290),
            new SimpleLocation("Chromepet",       "South West", 12.9516, 80.1439),
            new SimpleLocation("Pallavaram",      "South West", 12.9675, 80.1491),
            new SimpleLocation("Saidapet",        "Central",    13.0206, 80.2248),
            new SimpleLocation("Nungambakkam",    "Central",    13.0569, 80.2425),
            new SimpleLocation("Royapettah",      "Central",    13.0524, 80.2606),
            new SimpleLocation("Triplicane",      "Central",    13.0587, 80.2771),
            new SimpleLocation("Kodambakkam",     "West Central",13.0526,80.2225),
            new SimpleLocation("Ashok Nagar",     "Central",    13.0296, 80.2136),
            new SimpleLocation("Vadapalani",      "West Central",13.0501,80.2121),
            new SimpleLocation("Mogappair",       "North West", 13.0826, 80.1778),
            new SimpleLocation("Avadi",           "North West", 13.1147, 80.0982),
            new SimpleLocation("Red Hills",       "North",      13.1878, 80.1792)
    );

    private static final String[] CRIME_TYPES = {
            "Theft", "Burglary", "Robbery", "Vehicle Theft", "Cyber Crime",
            "Fraud", "Assault", "Vandalism", "Chain Snatching", "Harassment"
    };

    private static final int[] CRIME_WEIGHTS = {25, 10, 8, 15, 12, 10, 7, 5, 5, 3};
    private static final String[] DAY_NAMES = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};

    private static final Map<String, String[]> DESCRIPTIONS = new HashMap<>();
    static {
        DESCRIPTIONS.put("Theft", new String[]{
                "Petty theft reported near a commercial establishment",
                "Theft of personal belongings in a public area",
                "Shoplifting incident at a retail store",
                "Pickpocketing reported at a busy market"
        });
        DESCRIPTIONS.put("Burglary", new String[]{
                "Residential burglary reported; entry through rear window",
                "Commercial premises broken into during non-business hours",
                "House break-in reported; valuables stolen",
                "Office premises burglarised overnight"
        });
        DESCRIPTIONS.put("Robbery", new String[]{
                "Street robbery reported; victim confronted by perpetrators",
                "Robbery at ATM vicinity",
                "Armed robbery at a small business",
                "Bag snatching during early morning hours"
        });
        DESCRIPTIONS.put("Vehicle Theft", new String[]{
                "Two-wheeler reported stolen from parking area",
                "Car theft reported from residential street",
                "Vehicle stolen from commercial parking lot",
                "Motorcycle stolen during market visit"
        });
        DESCRIPTIONS.put("Cyber Crime", new String[]{
                "Victim defrauded via phishing link",
                "Online banking fraud reported",
                "Social media impersonation complaint",
                "OTP-based fraud reported; victim lost funds"
        });
        DESCRIPTIONS.put("Fraud", new String[]{
                "Cheating complaint filed against unknown person",
                "Real-estate fraud complaint registered",
                "Job offer scam reported",
                "Investment fraud complaint; victim lost savings"
        });
        DESCRIPTIONS.put("Assault", new String[]{
                "Physical altercation reported in public area",
                "Assault during a road-rage incident",
                "Assault complaint registered outside residential area",
                "Physical altercation at a commercial venue"
        });
        DESCRIPTIONS.put("Vandalism", new String[]{
                "Public property damaged by unknown persons",
                "Vehicle windshield damaged in parking area",
                "Graffiti and damage reported at public park",
                "Shop shutters damaged overnight"
        });
        DESCRIPTIONS.put("Chain Snatching", new String[]{
                "Gold chain snatched by two-wheeler-borne persons",
                "Chain snatching reported near temple premises",
                "Victim's necklace snatched at roadside",
                "Chain snatching incident on busy street"
        });
        DESCRIPTIONS.put("Harassment", new String[]{
                "Harassment complaint registered; offender fled",
                "Verbal harassment complaint registered",
                "Stalking and harassment complaint filed",
                "Harassment incident near public transport stop"
        });
    }

    public static void main(String[] args) throws IOException {
        Path targetPath = Paths.get("dataset/chennai_crime_synthetic.csv");
        if (args.length > 0) {
            targetPath = Paths.get(args[0]);
        }

        Files.createDirectories(targetPath.getParent());

        int count = 3000;
        Random random = new Random(SEED);
        LocalDate startDate = LocalDate.of(2020, 1, 1);
        LocalDate endDate = LocalDate.of(2024, 12, 31);
        long dayRange = startDate.until(endDate).toTotalMonths() * 30L;

        int[] cumWeights = new int[CRIME_WEIGHTS.length];
        cumWeights[0] = CRIME_WEIGHTS[0];
        for (int i = 1; i < CRIME_WEIGHTS.length; i++) cumWeights[i] = cumWeights[i - 1] + CRIME_WEIGHTS[i];

        try (BufferedWriter writer = Files.newBufferedWriter(targetPath, StandardCharsets.UTF_8)) {
            writer.write(METADATA_COMMENT);
            writer.write(CSV_HEADER);
            writer.newLine();

            for (int i = 1; i <= count; i++) {
                SimpleLocation loc = CHENNAI_LOCATIONS.get(random.nextInt(CHENNAI_LOCATIONS.size()));
                LocalDate date = startDate.plusDays(random.nextInt((int) Math.max(1, dayRange)));
                int hour = weightedHour(random);
                String crimeType = weightedSelect(CRIME_TYPES, cumWeights, random);
                String severity = pickSeverity(crimeType, random);
                String status = pickStatus(date, random);
                String[] descs = DESCRIPTIONS.getOrDefault(crimeType, new String[]{"Incident reported"});
                String description = descs[random.nextInt(descs.length)];

                double lat = loc.lat + (random.nextDouble() - 0.5) * 0.01;
                double lon = loc.lon + (random.nextDouble() - 0.5) * 0.01;

                LocalTime time = LocalTime.of(hour, random.nextInt(60), random.nextInt(60));
                String dayName = DAY_NAMES[date.getDayOfWeek().getValue() - 1];

                String line = String.join(",",
                        String.format("CMA-%06d", i),
                        date.format(DateTimeFormatter.ISO_LOCAL_DATE),
                        time.format(DateTimeFormatter.ofPattern("HH:mm:ss")),
                        String.valueOf(date.getYear()),
                        String.valueOf(date.getMonthValue()),
                        dayName,
                        String.valueOf(hour),
                        escapeCsv(loc.name),
                        escapeCsv(loc.zone),
                        escapeCsv(crimeType),
                        severity,
                        String.format("%.6f", lat),
                        String.format("%.6f", lon),
                        escapeCsv(description),
                        status
                );
                writer.write(line);
                writer.newLine();
            }
        }
        System.out.println("Successfully generated " + count + " records to " + targetPath.toAbsolutePath());
    }

    private static int weightedHour(Random rnd) {
        int roll = rnd.nextInt(100);
        if (roll < 40) return 17 + rnd.nextInt(5);
        if (roll < 55) {
            int[] night = {22, 23, 0, 1, 2};
            return night[rnd.nextInt(night.length)];
        }
        return rnd.nextInt(17);
    }

    private static String weightedSelect(String[] items, int[] cumWeights, Random rnd) {
        int roll = rnd.nextInt(cumWeights[cumWeights.length - 1]);
        for (int i = 0; i < cumWeights.length; i++) {
            if (roll < cumWeights[i]) return items[i];
        }
        return items[items.length - 1];
    }

    private static String pickSeverity(String crimeType, Random rnd) {
        return switch (crimeType) {
            case "Robbery", "Assault" -> {
                int r = rnd.nextInt(10);
                yield r < 4 ? "HIGH" : r < 8 ? "MEDIUM" : "LOW";
            }
            case "Burglary", "Chain Snatching" -> {
                int r = rnd.nextInt(10);
                yield r < 3 ? "HIGH" : r < 7 ? "MEDIUM" : "LOW";
            }
            case "Cyber Crime", "Fraud" -> {
                int r = rnd.nextInt(10);
                yield r < 2 ? "HIGH" : r < 6 ? "MEDIUM" : "LOW";
            }
            default -> {
                int r = rnd.nextInt(10);
                yield r < 1 ? "HIGH" : r < 5 ? "MEDIUM" : "LOW";
            }
        };
    }

    private static String pickStatus(LocalDate date, Random rnd) {
        long monthsAgo = date.until(LocalDate.now()).toTotalMonths();
        if (monthsAgo > 24) return rnd.nextInt(10) < 7 ? "CLOSED" : "UNDER_INVESTIGATION";
        if (monthsAgo > 6) return rnd.nextInt(10) < 5 ? "CLOSED" : "UNDER_INVESTIGATION";
        return rnd.nextInt(10) < 4 ? "REPORTED" : "UNDER_INVESTIGATION";
    }

    private static String escapeCsv(String value) {
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}
