package com.crimeanalyzer.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Represents a location-level crime prevention recommendation.
 *
 * <p>Recommendations are generated by {@code RecommendationService}
 * based on area crime patterns in the synthetic dataset.
 * They are generic, preventive, and location-level — they do NOT
 * profile individuals or demographic groups.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Recommendation {

    private String area;
    private String crimeType;

    /** Summary of the crime pattern observed in the synthetic data. */
    private String patternSummary;

    /** The peak hour window e.g. "18:00 – 21:00". */
    private String peakTimeWindow;

    /** Dominant severity level for this area–crime combination. */
    private String dominantSeverity;

    /** Hotspot classification: LOW | MODERATE | HIGH */
    private String hotspotLevel;

    /** Computed hotspot score (0.0 – 1.0). */
    private double hotspotScore;

    /** Total records matching this area–crime combination. */
    private long totalIncidents;

    /** Ordered list of preventive measure strings. */
    private List<String> preventiveMeasures;

    /** General advisory for this crime type. */
    private String generalAdvisory;
}
