package com.crimeanalyzer.service;

import com.crimeanalyzer.model.Location;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Generates a synthetic, reproducible crime dataset for Chennai.
 *
 * <p><strong>DISCLAIMER:</strong> All records generated by this class are
 * entirely fictional and created for academic demonstration. They do NOT
 * represent official Chennai crime statistics or real events.
 *
 * <p>Uses a fixed random seed for reproducibility. The generator:
 * <ul>
 *   <li>Distributes crime types with realistic-looking weights</li>
 *   <li>Models time-of-day patterns (evening peak, night activity)</li>
 *   <li>Assigns locations from a curated list of Chennai areas</li>
 *   <li>Applies severity probabilities per crime type</li>
 * </ul>
 *
 * <p>Algorithm complexity:
 * <ul>
 *   <li>Generation: O(n) where n = number of records</li>
 *   <li>Write: O(n) sequential I/O</li>
 * </ul>
 */
@Component
public class DatasetGenerator {

    private static final Logger log = LoggerFactory.getLogger(DatasetGenerator.class);

    /** Fixed seed for reproducible dataset generation. */
    private static final long SEED = 20240101L;

    private static final String CSV_HEADER =
        "crime_id,date,time,year,month,day_of_week,hour,area,zone,crime_type," +
        "severity,latitude,longitude,description,case_status";

    private static final String METADATA_COMMENT =
        "# SYNTHETIC DATASET - GENERATED FOR ACADEMIC DEMONSTRATION ONLY\n" +
        "# This data does NOT represent official Chennai crime statistics.\n" +
        "# Generated by: Chennai Crime Pattern Analyzer (College Capstone Project)\n" +
        "# Fixed seed: " + SEED + " - Dataset is fully reproducible.\n";

    // -------------------------------------------------------
    // Chennai area definitions
    // -------------------------------------------------------
    private static final List<Location> CHENNAI_LOCATIONS = List.of(
        new Location("Anna Nagar",      "North",      13.0850, 80.2101),
        new Location("T Nagar",         "Central",    13.0418, 80.2341),
        new Location("Adyar",           "South",      13.0012, 80.2565),
        new Location("Velachery",       "South",      12.9815, 80.2180),
        new Location("Tambaram",        "South West", 12.9249, 80.1000),
        new Location("Guindy",          "Central",    13.0067, 80.2206),
        new Location("Egmore",          "Central",    13.0732, 80.2609),
        new Location("Mylapore",        "Central",    13.0368, 80.2676),
        new Location("Perambur",        "North",      13.1142, 80.2329),
        new Location("Ambattur",        "North West", 13.1143, 80.1548),
        new Location("Porur",           "West",       13.0359, 80.1573),
        new Location("Sholinganallur",  "South East", 12.9010, 80.2279),
        new Location("Thoraipakkam",    "South East", 12.9244, 80.2290),
        new Location("Chromepet",       "South West", 12.9516, 80.1439),
        new Location("Pallavaram",      "South West", 12.9675, 80.1491),
        new Location("Saidapet",        "Central",    13.0206, 80.2248),
        new Location("Nungambakkam",    "Central",    13.0569, 80.2425),
        new Location("Royapettah",      "Central",    13.0524, 80.2606),
        new Location("Triplicane",      "Central",    13.0587, 80.2771),
        new Location("Kodambakkam",     "West Central",13.0526,80.2225),
        new Location("Ashok Nagar",     "Central",    13.0296, 80.2136),
        new Location("Vadapalani",      "West Central",13.0501,80.2121),
        new Location("Mogappair",       "North West", 13.0826, 80.1778),
        new Location("Avadi",           "North West", 13.1147, 80.0982),
        new Location("Red Hills",       "North",      13.1878, 80.1792)
    );

    private static final String[] CRIME_TYPES = {
        "Theft", "Burglary", "Robbery", "Vehicle Theft", "Cyber Crime",
        "Fraud", "Assault", "Vandalism", "Chain Snatching", "Harassment"
    };

    /** Weights must sum to ≤ 100 and align with CRIME_TYPES array. */
    private static final int[] CRIME_WEIGHTS = {25, 10, 8, 15, 12, 10, 7, 5, 5, 3};

    private static final String[] SEVERITIES = {"LOW", "MEDIUM", "HIGH"};
    private static final String[] STATUSES   = {"REPORTED", "UNDER_INVESTIGATION", "CLOSED"};
    private static final String[] DAY_NAMES  = {
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
    };

    // -------------------------------------------------------
    // Description templates keyed by crime type
    // -------------------------------------------------------
    private static final Map<String, String[]> DESCRIPTIONS = new HashMap<>();
    static {
        DESCRIPTIONS.put("Theft", new String[]{
            "Petty theft reported near a commercial establishment",
            "Theft of personal belongings in a public area",
            "Shoplifting incident at a retail store",
            "Pickpocketing reported at a busy market"
        });
        DESCRIPTIONS.put("Burglary", new String[]{
            "Residential burglary reported; entry through rear window",
            "Commercial premises broken into during non-business hours",
            "House break-in reported; valuables stolen",
            "Office premises burglarised overnight"
        });
        DESCRIPTIONS.put("Robbery", new String[]{
            "Street robbery reported; victim confronted by perpetrators",
            "Robbery at ATM vicinity",
            "Armed robbery at a small business",
            "Bag snatching during early morning hours"
        });
        DESCRIPTIONS.put("Vehicle Theft", new String[]{
            "Two-wheeler reported stolen from parking area",
            "Car theft reported from residential street",
            "Vehicle stolen from commercial parking lot",
            "Motorcycle stolen during market visit"
        });
        DESCRIPTIONS.put("Cyber Crime", new String[]{
            "Victim defrauded via phishing link",
            "Online banking fraud reported",
            "Social media impersonation complaint",
            "OTP-based fraud reported; victim lost funds"
        });
        DESCRIPTIONS.put("Fraud", new String[]{
            "Cheating complaint filed against unknown person",
            "Real-estate fraud complaint registered",
            "Job offer scam reported",
            "Investment fraud complaint; victim lost savings"
        });
        DESCRIPTIONS.put("Assault", new String[]{
            "Physical altercation reported in public area",
            "Assault during a road-rage incident",
            "Assault complaint registered outside residential area",
            "Physical altercation at a commercial venue"
        });
        DESCRIPTIONS.put("Vandalism", new String[]{
            "Public property damaged by unknown persons",
            "Vehicle windshield damaged in parking area",
            "Graffiti and damage reported at public park",
            "Shop shutters damaged overnight"
        });
        DESCRIPTIONS.put("Chain Snatching", new String[]{
            "Gold chain snatched by two-wheeler-borne persons",
            "Chain snatching reported near temple premises",
            "Victim's necklace snatched at roadside",
            "Chain snatching incident on busy street"
        });
        DESCRIPTIONS.put("Harassment", new String[]{
            "Harassment complaint registered; offender fled",
            "Verbal harassment complaint registered",
            "Stalking and harassment complaint filed",
            "Harassment incident near public transport stop"
        });
    }

    // -------------------------------------------------------
    // Public API
    // -------------------------------------------------------

    /**
     * Generates {@code count} synthetic crime records and writes them
     * to the given file path.
     *
     * @param outputPath absolute path to the output CSV file
     * @param count      number of records to generate (recommended 2000–5000)
     */
    public void generate(Path outputPath, int count) throws IOException {
        log.info("Generating {} synthetic crime records → {}", count, outputPath);

        Files.createDirectories(outputPath.getParent());

        Random random = new Random(SEED);
        LocalDate startDate = LocalDate.of(2020, 1, 1);
        LocalDate endDate   = LocalDate.of(2024, 12, 31);
        long dayRange = startDate.until(endDate).toTotalMonths() * 30L;

        // Build cumulative weight array for weighted random selection
        int[] cumWeights = buildCumulativeWeights(CRIME_WEIGHTS);

        try (BufferedWriter writer = Files.newBufferedWriter(outputPath, StandardCharsets.UTF_8)) {
            writer.write(METADATA_COMMENT);
            writer.write(CSV_HEADER);
            writer.newLine();

            for (int i = 1; i <= count; i++) {
                CrimeRowData row = buildRow(i, random, startDate, dayRange, cumWeights);
                writer.write(row.toCsvLine());
                writer.newLine();
            }
        }

        log.info("Dataset written: {} records to {}", count, outputPath);
    }

    // -------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------

    private CrimeRowData buildRow(int index, Random rnd,
                                   LocalDate startDate, long dayRange,
                                   int[] cumWeights) {
        // Location
        Location loc = CHENNAI_LOCATIONS.get(rnd.nextInt(CHENNAI_LOCATIONS.size()));

        // Date — uniform distribution across range
        LocalDate date = startDate.plusDays(rnd.nextInt((int) Math.max(1, dayRange)));

        // Hour — weighted towards evening (17–21) and late night (22–02)
        int hour = weightedHour(rnd);

        // Crime type via weighted selection
        String crimeType = weightedSelect(CRIME_TYPES, cumWeights, rnd);

        // Severity probabilities differ by crime type
        String severity = pickSeverity(crimeType, rnd);

        // Case status
        String status = pickStatus(date, rnd);

        // Description
        String[] descs = DESCRIPTIONS.getOrDefault(crimeType, new String[]{"Incident reported"});
        String description = descs[rnd.nextInt(descs.length)];

        // Add small coordinate jitter (±0.005 degrees ≈ ±500m)
        double lat = loc.getLatitude()  + (rnd.nextDouble() - 0.5) * 0.01;
        double lon = loc.getLongitude() + (rnd.nextDouble() - 0.5) * 0.01;

        LocalTime time = LocalTime.of(hour, rnd.nextInt(60), rnd.nextInt(60));
        String dayName = DAY_NAMES[date.getDayOfWeek().getValue() - 1];

        return new CrimeRowData(
            String.format("CMA-%06d", index),
            date, time,
            date.getYear(), date.getMonthValue(), dayName, hour,
            loc.getAreaName(), loc.getZone(),
            crimeType, severity,
            lat, lon, description, status
        );
    }

    /** Returns a time-of-day hour with realistic peak patterns. */
    private int weightedHour(Random rnd) {
        // 40% chance: evening peak 17–21
        // 15% chance: late night 22–02
        // 45% chance: rest of day
        int roll = rnd.nextInt(100);
        if (roll < 40) return 17 + rnd.nextInt(5);          // 17, 18, 19, 20, 21
        if (roll < 55) {
            int[] night = {22, 23, 0, 1, 2};
            return night[rnd.nextInt(night.length)];
        }
        return rnd.nextInt(17); // 0–16
    }

    /** Weighted selection from an array using cumulative weights. */
    private String weightedSelect(String[] items, int[] cumWeights, Random rnd) {
        int roll = rnd.nextInt(cumWeights[cumWeights.length - 1]);
        for (int i = 0; i < cumWeights.length; i++) {
            if (roll < cumWeights[i]) return items[i];
        }
        return items[items.length - 1];
    }

    private int[] buildCumulativeWeights(int[] weights) {
        int[] cum = new int[weights.length];
        cum[0] = weights[0];
        for (int i = 1; i < weights.length; i++) cum[i] = cum[i - 1] + weights[i];
        return cum;
    }

    private String pickSeverity(String crimeType, Random rnd) {
        return switch (crimeType) {
            case "Robbery", "Assault" -> {
                int r = rnd.nextInt(10);
                yield r < 4 ? "HIGH" : r < 8 ? "MEDIUM" : "LOW";
            }
            case "Burglary", "Chain Snatching" -> {
                int r = rnd.nextInt(10);
                yield r < 3 ? "HIGH" : r < 7 ? "MEDIUM" : "LOW";
            }
            case "Cyber Crime", "Fraud" -> {
                int r = rnd.nextInt(10);
                yield r < 2 ? "HIGH" : r < 6 ? "MEDIUM" : "LOW";
            }
            default -> {
                int r = rnd.nextInt(10);
                yield r < 1 ? "HIGH" : r < 5 ? "MEDIUM" : "LOW";
            }
        };
    }

    private String pickStatus(LocalDate date, Random rnd) {
        long monthsAgo = date.until(LocalDate.now()).toTotalMonths();
        if (monthsAgo > 24) return rnd.nextInt(10) < 7 ? "CLOSED" : "UNDER_INVESTIGATION";
        if (monthsAgo > 6)  return rnd.nextInt(10) < 5 ? "CLOSED" : "UNDER_INVESTIGATION";
        return rnd.nextInt(10) < 4 ? "REPORTED" : "UNDER_INVESTIGATION";
    }

    // -------------------------------------------------------
    // Inner record for one CSV row
    // -------------------------------------------------------

    private record CrimeRowData(
        String crimeId, LocalDate date, LocalTime time,
        int year, int month, String dayOfWeek, int hour,
        String area, String zone, String crimeType, String severity,
        double latitude, double longitude, String description, String caseStatus
    ) {
        private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ISO_LOCAL_DATE;
        private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("HH:mm:ss");

        String toCsvLine() {
            return String.join(",",
                crimeId,
                date.format(DATE_FMT),
                time.format(TIME_FMT),
                String.valueOf(year),
                String.valueOf(month),
                dayOfWeek,
                String.valueOf(hour),
                escapeCsv(area),
                escapeCsv(zone),
                escapeCsv(crimeType),
                severity,
                String.format("%.6f", latitude),
                String.format("%.6f", longitude),
                escapeCsv(description),
                caseStatus
            );
        }

        private String escapeCsv(String value) {
            if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
                return "\"" + value.replace("\"", "\"\"") + "\"";
            }
            return value;
        }
    }
}
